config/routes.rb
Shikocc::Application.routes.draw do

  root :to => 'pages#index'

  #рассылка
  get '/user_s' => 'user#start'
  get '/user_unsubscribe/:id' => 'user#unsubscribe', :as => :unsubscribe
  #рассылка


  #начало роуты для корзины и заказов
  post 'order_add_product' => 'order#order_add_product'
  delete '/products_order_destroy/:id/:product_id' => 'order#products_order_destroy', :as => :products_order_destroy
  get '/ajax/mini_cart' => 'ajax#mini_cart'
  get 'cart' => 'order#cart', :as => :cart
  get '/order/confirm/:id' => 'order#confirm', :as => :order_confirm
  put 'order/create/:id' => 'order#create'
  get 'order/:id' => 'order#show'
  #конец роуты для корзины и заказов


  resources :feedbacks, :only => [:index, :create]

  #begin ajax
  get '/ajax/product/:id' => 'ajax#product'
  #end ajax


  get '/admin' => 'admin/dashboard#index'

  #begin static pages
  get 'contacts' => 'pages#contacts', :as => :contacts
  get 'about' => 'pages#about', :as => :about
  get 'fashion' => 'pages#fashion', :as => :fashion
  #end static pages


  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  namespace :admin do
    resources :pages do
      collection do

        post :rebuild

        get ':id/edit' => 'pages#edit'
        get '*section/:id/edit' => 'pages#edit'

        get ':id' => 'pages#show'
        get '*section/:id' => 'pages#show'

        get ':id' => 'pages#new'

        put '*section/:id' => 'pages#update'
        put ':id' => 'pages#update'

        delete ':id' => 'pages#destroy'
        delete '*section/:id' => 'pages#destroy'

      end
    end
  end

  #begin хаки для страниц из-за ёбнутейшего роутинга ниже
  get '/service/:id' => 'pages#show'
  #end хаки для страниц из-за ёбнутейшего роутинга ниже


  #ёбнутейший роутинг начало
  get '/shop/' => 'categories#index', :as => :shop
  get '/shop/:id' => 'categories#category', :as => :category
  resources :categories, :only => [], :path => '/shop/' do
    get '/:id' => 'products#show', :as => :product
  end
  #ёбнутейший роутинг конец

  resources :pages, :path => "/", :only => [:index, :show]

end

app/models/order.rb
# encoding: utf-8
class Order < ActiveRecord::Base

  attr_accessible :username, :surname, :email, :phone, :address, :comment, :data,
                  :price, :payment, :order_confirm, :confirm

  attr_reader :items
  #
  validates_length_of :username, :in => 2..50, :message => "Имя должно быть длинной не менее 2 и не более 50 символов"
  validates :email, :format => {:with => /[A-Za-z0-9._%+-]+@([A-Za-z0-9-]+\.)+([A-Za-z0-9]{2,4}|museum)/,
                                :message => "Не правильно указан адрес e-mail"}
  validates_length_of :phone, :in => 5..15, :message => "Не указан телефон"
  validates_length_of :address, :in => 5..300, :message => "Не указан адрес"

  #begin объявлеям связь с упражнениями многие ко многим, через соединительную модель motions_programs
  has_many :products_orders
  has_many :products, :through => :products_orders
  #end объявлеям связь с упражнениями многие ко многим, через соединительную модель motions_programs

end

app/controllers/order_controller.rb
class OrderController < ApplicationController


  def order_add_product

    if session[:order_id]
      @order = Order.find(session[:order_id])
      @order_id = @order.id
    else
      @order = Order.new
      @order.save(:validate => false)
      @order_id = @order.id
      session[:order_id] = @order_id
    end


    @products_order = ProductsOrder.where("product_id = ? AND order_id = ?", params[:id], @order_id).first

    #общая стоимость заказа
    @product = Product.find(params[:id])
    @order.update_attribute(:price, @order.price.to_i + @product.price.to_i)
    @order.update_attribute(:confirm, "В процессе")

    if @products_order
      @products_order.update_attributes(:order_id => @order_id, :product_id => params[:id], :size => params[:size], :sum => @products_order.sum + 1)
    else
      @products_order = ProductsOrder.new(:order_id => @order_id, :product_id => params[:id], :size => params[:size], :sum => 1)
      @products_order.save
    end


    @quantity = 0
    for product in @order.products
      @products_orders = ProductsOrder.where("product_id = ? AND order_id = ?", product.id, @order_id).first
      @count = @products_orders.sum
      @quantity = @quantity + @count
    end

    respond_to do |format|
      format.js {}
      format.json { render :json => @order, :status => :created, :location => @order }
    end

  end


  def products_order_destroy
    @order = Order.find(params[:id])
    @product = Product.find(params[:product_id])

    #общая стоимость заказа
    @products_order = ProductsOrder.where("product_id = ? AND order_id = ?", params[:product_id], params[:id]).first
    @count = @order.price.to_i - @product.price.to_i * @products_order.sum
    @order.update_attribute(:price, @count)

    @order.products.delete(@product)

    respond_to do |format|
      format.html { redirect_to cart_url(@order) }
      format.json { head :no_content }
    end
  end


  def cart
    if session[:order_id]
      @order = Order.find(session[:order_id])
    else
      @order = Order.new
      @order.save(:validate => false)
      session[:order_id] = @order.id
    end
    @order_id = @order.id
    @products = @order.products

    @price = @order.price

    @meta_title = "Корзина"
  end

  def confirm
    @order = Order.find(params[:id])

    @order_id = params[:id]
    @products = @order.products
    @price = @order.price
  end


  def create
    @order = Order.find(params[:id])
    if @order.update_attributes(params[:order])
      session[:order_id] = nil
      redirect_to :action => :show, :id => @order.id
      OrderMailer.order_cofirm(@order).deliver
      OrderMailer.order_cofirm_user(@order).deliver
    else
      render :action => :confirm
    end
  end

  def show
    @order = Order.find(params[:id])
    @order_id = @order.id
    @products = @order.products
    @price = @order.price
  end

end

app/views/order/_form.html.haml
= form_for @order, :url => { :action => :create } do |f|

  .cart-box.clearfix
    %input{:type=>"hidden", :name=>"order[confirm]", :value=> 'Новый'}

    %dl.username
      %dt Ваше имя *
      %dd.field= f.text_field :username
      - if @order.errors.any?
        %dd.error= @order.errors.messages[:username].join

    %dl
      %dt Электронная почта *
      %dd.field= f.text_field :email
      - if @order.errors.any?
        %dd.error= @order.errors.messages[:email].join

    %dl
      %dt Телефон для связи *
      %dd.field= f.text_field :phone
      - if @order.errors.any?
        %dd.error= @order.errors.messages[:phone].join

    %dl
      %dt Адрес доставки *
      %dd.field= f.text_field :address
      - if @order.errors.any?
        %dd.error= @order.errors.messages[:address].join


    %dl
      %dt Комментарий к заказу
      %dd.field= f.text_area :comment

  .cart-order-confirm.clearfix
    = link_to "< Вернуться в корзину", cart_path
    %input.button{:type=>"submit", :value=>"Подтвердить заказ"}

app/views/order/cart.haml
%h1.inner-page-title Корзина

.inner-page

  .breadcrumbs
    = link_to 'Главная', root_path
    %span.breadcrumbs-d >
    =link_to 'Магазин', shop_path
    %span.breadcrumbs-d >
    Корзина





  -if @products.length != 0

    %table.cart-table
      %tr
        %th.image Изображение
        %th Название
        %th Описание
        %th.qa кол-во
        %th Цена
        %th

        -for item in @products
          -@products_order = ProductsOrder.where("product_id = ? AND order_id = ?", item.id, @order_id).first
          -@count = @products_order.sum
          -@size = @products_order.size

          %tr
            %td.image
              -if item.attachments.find_last
                = image_tag item.attachments.find_last.file_url(:mini)
              -else
                %img{:src => '/images/nophoto_small.png'}
            %td.name
              %div= link_to item.title, [item.category, item]
              .size
                Размер:
                %b=@size

            %td
              .desc= item.desc
            %td.qa=@count
            %td.price
              = item.price.to_i * @count
              руб.
            %td.remove=link_to "", products_order_destroy_path(@order, item), :method => :delete, :class => "sprite delete"

    .order-sum
      Итоговая стоимость заказа:
      %b
        = @price
        руб

    .order-confirm.clearfix
      = link_to "< Вернуться к покупкам", shop_path
      = link_to "Оформить заказ", order_confirm_path(@order), :class => "button cart-order"

  -else
    %h1 Ваша корзина пуста

app/views/order/confirm.haml
%h1.inner-page-title Оформление

.inner-page

  .breadcrumbs
    = link_to 'Главная', root_path
    %span.breadcrumbs-d >
    =link_to 'Магазин', shop_path
    %span.breadcrumbs-d >
    =link_to 'Корзина', cart_path
    %span.breadcrumbs-d >
    Оформление

  .clearfix

    .box-right.confirm
      = render 'form'

    .box-left
      .js-mini_cart= render_cell :cart, :mini_cart

app/views/order/order_add_product.js.erb
//$("<div class='add_cart_success'><div class='add_cart_success-bg'></div><div>Товар добавлен в корзину</div></div>").appendTo("body");

$(".js-cart").html("<%= @quantity %>");


//setTimeout(function(){
//    $('.add_cart_success').remove();
//},700)

app/views/order/show.haml
%h1.inner-page-title
  Заказ №
  = @order.id

.inner-page

  .breadcrumbs
    = link_to 'Главная', root_path
    %span.breadcrumbs-d >
    =link_to 'Магазин', shop_path
    %span.breadcrumbs-d >
    =link_to 'Корзина', cart_path
    %span.breadcrumbs-d >
    Заказ
    = @order.id

  .text-page

    .title_h2
      .delimiter
        .sprite.us_t
      %h2 Заказ успешно оформлен
      .delimiter
        .sprite.us_b

    .b_info
      %div В ближайшее время с Вами свяжется наш менеджер для подтверждения заказа.
      %div Всю информацию по заказу Вы можете узнать у нашего менеджера позвонив по телефону
      %b +7 (915) 199-86-10
      %div
        Номер Вашего заказа:
        %b= @order.id


    .title_h2
      .delimiter
        .sprite.us_t
      %h2 Содержимое заказа
      .delimiter
        .sprite.us_b


    -if @products.length != 0

      %table.cart-table
        %tr
          %th.image Изображение
          %th Название
          %th Описание
          %th.qa кол-во
          %th Цена

          -for item in @products
            -@products_order = ProductsOrder.where("product_id = ? AND order_id = ?", item.id, @order_id).first
            -@count = @products_order.sum
            -@size = @products_order.size

            %tr
              %td.image
                -if item.attachments.find_last
                  = image_tag item.attachments.find_last.file_url(:mini)
                -else
                  %img{:src => '/images/nophoto_small.png'}
              %td.name
                %div= link_to item.title, [item.category, item]
                .size
                  Размер:
                  %b=@size

              %td
                .desc= item.desc
              %td.qa=@count
              %td.price
                = item.price.to_i * @count
                руб.

      .order-sum
        Итоговая стоимость заказа:
        %b
          = @price
          руб

    .title_h2
      .delimiter
        .sprite.us_t
      %h2= link_to "Вернуться к покупкам", shop_path
      .delimiter
        .sprite.us_b