config/routes.rb
Shikocc::Application.routes.draw do

  root :to => 'pages#index'

  #рассылка
  get '/user_s' => 'user#start'
  get '/user_unsubscribe/:id' => 'user#unsubscribe', :as => :unsubscribe
  #рассылка


  #начало роуты для корзины и заказов
  post 'order_add_product' => 'order#order_add_product'
  delete '/products_order_destroy/:id/:product_id' => 'order#products_order_destroy', :as => :products_order_destroy
  get '/ajax/mini_cart' => 'ajax#mini_cart'
  get 'cart' => 'order#cart', :as => :cart
  get '/order/confirm/:id' => 'order#confirm', :as => :order_confirm
  put 'order/create/:id' => 'order#create'
  get 'order/:id' => 'order#show'
  #конец роуты для корзины и заказов


  resources :feedbacks, :only => [:index, :create]

  #begin ajax
  get '/ajax/product/:id' => 'ajax#product'
  #end ajax


  get '/admin' => 'admin/dashboard#index'

  #begin static pages
  get 'contacts' => 'pages#contacts', :as => :contacts
  get 'about' => 'pages#about', :as => :about
  get 'fashion' => 'pages#fashion', :as => :fashion
  #end static pages


  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  namespace :admin do
    resources :pages do
      collection do

        post :rebuild

        get ':id/edit' => 'pages#edit'
        get '*section/:id/edit' => 'pages#edit'

        get ':id' => 'pages#show'
        get '*section/:id' => 'pages#show'

        get ':id' => 'pages#new'

        put '*section/:id' => 'pages#update'
        put ':id' => 'pages#update'

        delete ':id' => 'pages#destroy'
        delete '*section/:id' => 'pages#destroy'

      end
    end
  end

  #begin хаки для страниц из-за ёбнутейшего роутинга ниже
  get '/service/:id' => 'pages#show'
  #end хаки для страниц из-за ёбнутейшего роутинга ниже


  #ёбнутейший роутинг начало
  get '/shop/' => 'categories#index', :as => :shop
  get '/shop/:id' => 'categories#category', :as => :category
  resources :categories, :only => [], :path => '/shop/' do
    get '/:id' => 'products#show', :as => :product
  end
  #ёбнутейший роутинг конец

  resources :pages, :path => "/", :only => [:index, :show]

end

app/views/shared/_breadcrumbs.haml
.breadcrumbs
  = link_to 'Главная', '/'
  >>
  = link_to 'Page', '/'
  >>
  %span Page

app/views/shared/_counter.erb
<!-- Yandex.Metrika counter -->
<script type="text/javascript">
	(function (d, w, c) {
		(w[c] = w[c] || []).push(function() {
			try {
				w.yaCounter22769464 = new Ya.Metrika({id:22769464,
					webvisor:true,
					clickmap:true,
					trackLinks:true,
					accurateTrackBounce:true});
			} catch(e) { }
		});

		var n = d.getElementsByTagName("script")[0],
				s = d.createElement("script"),
				f = function () { n.parentNode.insertBefore(s, n); };
		s.type = "text/javascript";
		s.async = true;
		s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

		if (w.opera == "[object Opera]") {
			d.addEventListener("DOMContentLoaded", f, false);
		} else { f(); }
	})(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="//mc.yandex.ru/watch/22769464" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

app/views/shared/_footer.haml
#footer
  .container
    .info.clearfix
      %ul.nav
        %li{:class => "#{'selected' if @product || @categories || @category}"}=link_to 'магазин', shop_path
        %li{:class => "#{'selected' if @about}"}=link_to 'О компании', about_path
        %li{:class => "#{'selected' if @contacts}"}=link_to 'Контакты', contacts_path
        %li{:class => "#{'selected' if @cart}"}
          =link_to cart_path do
            = render_cell :cart, :show

      .contacts.clearfix
        .phone Тел: +7 (915) 199-86-10
        .e-mail
          e-mail:
          %a{:href => 'mailto:volare.italy@mail.ru'} volare.italy@mail.ru

      .social
        =link_to 'http://vk.com/club53662913', {:target => '_blank', :class => 'social_icon'} do
          .sprite.vk
        =link_to 'http://instagram.com/volareitaly', {:target => '_blank', :class => 'social_icon'} do
          .sprite.in

    .copyright 
      © Volare. Все права защищены.
      .create 
        сделано в 
        =link_to 'http://rocket-web.ru/', {:target => '_blank'} do
          =image_tag "rocket-web.png", alt: "Веб студия Rocket-web"
          

app/views/shared/_header.haml
.header

  .contacts
    Тел.: +7 (915) 199-86-10
    &nbsp;
    E-mail: <a href="mailto:volare.italy@mail.ru">volare.italy@mail.ru</a>

  =link_to "LOGO", "/", :class => 'logo'

  %ul.nav.left
    %li{:class => "#{'selected' if @product || @categories || @category}"}=link_to 'магазин', shop_path
    %li{:class => "#{'selected' if @about}"}=link_to 'О компании', about_path

  %ul.nav.right
    %li{:class => "#{'selected' if @contacts}"}=link_to 'Контакты', contacts_path
    %li{:class => "#{'selected' if @cart}"}
      =link_to cart_path do
        = render_cell :cart, :show

app/views/shared/_mini_cart.haml
-if @products.length > 0
  %dl.mini_cart
    %dt КОРЗИНА
    -@products.each do |product|
      %dd
        %div=link_to product.title, [product.category, product]
        %div
          Кол-во:
          -@products_order = ProductsOrder.where("product_id = ? AND order_id = ?", product.id, @order_id).first
          -@count = @products_order.sum
          =@count
        %div
          Цена:
          =product.price.to_i * @count
          руб
    %dd.sum
      Сумма:
      =@price
      руб

    %dd{:style=> "padding:10px 0 0 0"}
      %a{:class=> "button cart-order", :href=> "/cart"} Оформить заказ

app/views/shared/_product.haml
%li.product.js-product
  .photo
    -if product.attachments.find_last
      = link_to([product.category, product]) do
        = image_tag product.attachments.find_last.file_url(:thumb)
    -else
      = link_to([product.category, product]) do
        %img{:src => '/images/nophoto_small.png'}

  = link_to [product.category, product], :class => 'title' do
    «
    =product.title
    »

  %dl.product-params
    %dt Цена:
    %dd
      = product.price.to_i
      руб
  %dl.product-params
    %dt Размер:
    %dd.weight-cont.js-weight-cont
      .weight.js-weight 36
      .weight.js-weight 37
      .weight.js-weight.selected 38
      .weight.js-weight 39
      .weight.js-weight 40
      .weight.js-weight 41
  .cart-add.js-order-add{:data => {:id => product.id, :size => '38'}} Купить

app/views/shared/_product_slides.erb
<div class="products-slide clearfix">
  <div class="sprite prev"></div>
  <div class="sprite next"></div>
  <div class="slides_container clearfix">
    <%- @count = 0 %>
    <%- for product in @products do %>

        <%- if @count <=3 %>

            <%- if @count == 0 %>
                <ul class="products-slide-item">
            <%- end %>

            <%- @count = @count + 1 %>

            <%= render :partial => 'shared/product', :object => product %>

            <%- if @count == 3 %>
                </ul>
                <%- @count = 0 %>
            <%- end %>

        <%- end %>

    <%- end %>
  </div>
</div>